default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  strava_client_id: <%= ENV["STRAVA_CLIENT_ID"] %>
  strava_client_secret: <%= ENV["STRAVA_CLIENT_SECRET"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
