default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  strava_client_id: <%= ENV["STRAVA_CLIENT_ID"] %>
  strava_client_secret: <%= ENV["STRAVA_CLIENT_SECRET"] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
