#!/usr/bin/env ruby

require 'rubygems'
require 'pry'
require 'pry-nav'
require 'yaml'

require_relative '../lib/plan_parser/training_peaks'

filename = ARGV.shift
raise "please specify a FILENAME" if filename.nil?

Day = PlanParser::TrainingPeaks::Day
Activity = PlanParser::TrainingPeaks::Activity
Post = PlanParser::TrainingPeaks::Post

results = {}
date = Day.new('header')
activity = Activity.new('header')
post = Post.new('header')

PlanParser::TrainingPeaks.each(filename) do |cat, line|
  # puts [cat, line].inspect

  case cat
  when 'date'
    year = line =~ %r{\A1\/} ? '2015' : '2014'
    results[line] ||= Day.new("#{line}/#{year}")
    date = results[line]
  when 'tag'
    activity = Activity.new(line, nil, nil)
    date.activities << activity
  when 'duration'
    activity.duration = line
  when 'distance'
    activity.distance = line
  when 'label'
    post = Post.new(line, nil)
    activity.posts << post
  when 'notes'
    post.notes = line
  end
end

puts results.to_yaml
