#!/usr/bin/env ruby

require 'rubygems'
require 'ankusa'
require 'ankusa/file_system_storage'
require 'pry'
require 'pry-nav'

require_relative '../lib/plan_parser/training_peaks'

storage = Ankusa::FileSystemStorage.new File.expand_path("../training-data", __FILE__)
c = Ankusa::NaiveBayesClassifier.new storage

c.train :skip, ''

filename = ARGV.shift
raise "please specify a FILENAME" if filename.nil?

10.times do
  PlanParser::TrainingPeaks.each(filename) do |cat, line|
    puts cat, line
    c.train cat.to_sym, line
  end

  print "."
  storage.save
end

File.open(filename, 'r').each do |line|
  puts [line.strip,  c.classify(line.strip), '']
end
